export const SET_THEME = 'SET_THEME';
export const SET_NEW_URL = 'SET_NEW_URL';

export const SET_CURRENT_WEATHER = 'SET_CURRENT_WEATHER';
export const SET_WEATHER_ON5_DAYS = 'SET_WEATHER_ON5_DAYS';

export const SET_NEW_LOCATION = 'SET_NEW_LOCATION';

export const SET_FAVORITE_LOCATION = 'SET_FAVORITE_LOCATION';